# Generated by Django 4.2.6 on 2023-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
    ]
